version: '3.7'

services:
  admin:
    image: 14.241.226.192:5000/dsfm_pepsi_cooler-admin-${CI_ENVIRONMENT_SLUG}:${CI_PIPELINE_ID}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - VERSION=${VERSION}
    
    container_name: dsfm_pepsi_cooler-admin
    ports:
      - '${HOST_PORT}:5000'

networks:
  default:
    external:
      name: nginx-proxy
