export const GET_CALL_COVERAGE_CHART = 'features/charts/GET_CALL_COVERAGE_CHART';
export const GET_CALL_COVERAGE_CHART_SUCCESS = 'features/charts/GET_CALL_COVERAGE_CHART_SUCCESS';
export const GET_CALL_COVERAGE_CHART_ERROR = 'features/charts/GET_CALL_COVERAGE_CHART_ERROR';

export const GET_CALL_ACHIEVEMENT_CHART = 'features/charts/GET_CALL_ACHIEVEMENT_CHART';
export const GET_CALL_ACHIEVEMENT_CHART_SUCCESS = 'features/charts/GET_CALL_ACHIEVEMENT_CHART_SUCCESS';
export const GET_CALL_ACHIEVEMENT_CHART_ERROR = 'features/charts/GET_CALL_ACHIEVEMENT_CHART_ERROR';

export const GET_NONCOOPERATION_REASONS_CHART = 'features/charts/GET_NONCOOPERATION_REASONS_CHART';
export const GET_NONCOOPERATION_REASONS_CHART_SUCCESS = 'features/charts/GET_NONCOOPERATION_REASONS_CHART_SUCCESS';
export const GET_NONCOOPERATION_REASONS_CHART_ERROR = 'features/charts/GET_NONCOOPERATION_REASONS_CHART_ERROR';

export const GET_NONCOOPERATION_REASONS_TRENDS_CHART = 'features/charts/GET_NONCOOPERATION_REASONS_TRENDS_CHART';
export const GET_NONCOOPERATION_REASONS_TRENDS_CHART_SUCCESS = 'features/charts/GET_NONCOOPERATION_REASONS_TRENDS_CHART_SUCCESS';
export const GET_NONCOOPERATION_REASONS_TRENDS_CHART_ERROR = 'features/charts/GET_NONCOOPERATION_REASONS_TRENDS_CHART_ERROR';

export const GET_FRIDGES_DISPLAY_RESULT_CHART = 'features/charts/GET_FRIDGES_DISPLAY_RESULT_CHART';
export const GET_FRIDGES_DISPLAY_RESULT_CHART_SUCCESS = 'features/charts/GET_FRIDGES_DISPLAY_RESULT_CHART_SUCCESS';
export const GET_FRIDGES_DISPLAY_RESULT_CHART_ERROR = 'features/charts/GET_FRIDGES_DISPLAY_RESULT_CHART_ERROR';

export const GET_FRIDGES_COMPLIANCE_CHART = 'features/charts/GET_FRIDGES_COMPLIANCE_CHART';
export const GET_FRIDGES_COMPLIANCE_CHART_SUCCESS = 'features/charts/GET_FRIDGES_COMPLIANCE_CHART_SUCCESS';
export const GET_FRIDGES_COMPLIANCE_CHART_ERROR = 'features/charts/GET_FRIDGES_COMPLIANCE_CHART_ERROR';